config/routes.rb
Rails.application.routes.draw do

resources :ratings, only: [:show, :new, :create]
resources :labels, only: [:show]

resources :advertisements, :questions
resources :users, only: [:new, :create, :show]
resources :sessions, only: [:new, :create, :destroy]

resources :topics do
  resources :posts, except: [:index]
  resources :sponsored_posts, except: [:index]
end

#resources :posts, only: [] do
resources :posts do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
end

post 'users/confirm' => 'users#confirm'

get 'about' => 'welcome#about'

get 'faq' => 'welcome#faq'
  
root to: 'welcome#index'
  
  
  namespace :api do
     namespace :v1 do
   
       resources :users, only: [:index, :show, :create, :update]
       
       
       resources :topics do
           resources :topics, except: [:edit, :new]
           resources :posts, only: [:create]
       end
       
       resources :posts, only: [:update, :destroy, :show]
       resources :comments, only: [:show]
      
      end
   end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
  def contact
  end
  
  def faq
  end
  



end

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>

<%= link_to "Follow me", "https://www.facebook.com/profile.php?id=100008173448385", class: "social-btn" %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Bloccit</h1>
   <p>Bloccit is a resource for sharing links with your friends!</p>
   <p>
     <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
     <%= link_to "Sign In", new_session_path %> or
   </p>
 </div>
 
 <div class="row">
   <div class="col-md-4">
     <h2>Solves world hunger</h2>
     <p>Bloccit will deliver food and water to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Eliminates poverty</h2>
     <p>Bloccit will deliver money and education to those in need, all over the world.</p>
   </div>
   <div class="col-md-4">
     <h2>Makes you better looking</h2>
     <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
   </div>
 </div>