config/routes.rb
Rails.application.routes.draw do

resources :ratings, only: [:show, :new, :create]
resources :labels, only: [:show]

resources :advertisements, :questions
resources :users, only: [:new, :create, :show]
resources :sessions, only: [:new, :create, :destroy]

resources :topics do
  resources :posts, except: [:index]
  resources :sponsored_posts, except: [:index]
end

#resources :posts, only: [] do
resources :posts do
  resources :comments, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
end

post 'users/confirm' => 'users#confirm'

get 'about' => 'welcome#about'

get 'faq' => 'welcome#faq'
  
root to: 'welcome#index'
  
  
  namespace :api do
     namespace :v1 do
   
       resources :users, only: [:index, :show, :create, :update]
       
       
       resources :topics do
           resources :topics, except: [:edit, :new]
           resources :posts, only: [:create]
       end
       
       resources :posts, only: [:update, :destroy, :show]
       resources :comments, only: [:show]
      
      end
   end


end

app/models/rating.rb
class Rating < ActiveRecord::Base
enum name: [ :PG, :PG13, :R ]

#has_many :rates

   belongs_to :ratable, polymorphic: true
   
    #has_many :posts, through: :rate, source: :ratable, source_type: :Post
   #has_many :topics, through: :rating, source: :ratable, source_type: :Topic


    # def self.update_ratings(rating_string)
    #  new_ratings = []

    #  unless rating_string.nil? || rating_string.empty?

       
    #    rating_name = rating_string
    #    new_rating = Rating.find_or_create_by(name: rating_name)
       
    #  end
    #  new_ratings
    # end
      
    
   
end
   
   

   

  

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    

before_action :require_sign_in

    def show
    @rating = Rating.find(params[:id])
    end


   def new
    @rating = Rating.new(ratable_id: params[:ratable_id], ratable_type: params[:ratable_type])
    
   end
   
   def create
       @rating = Rating.new(rating_params)
       
       if @rating.save
           flash[:notice] = "Your rating has been saved"
           redirect_to @rating.ratable
           
       else
           flash[:notice] = "Your rating was not saved"
           render :new
       end
   
  
   end
   
   private
   
   def rating_params
       params.require(:rating).permit(:name, :ratable_id, :ratable_type)
       
   end
  
    
    
end

app/helpers/ratings_helper.rb
module RatingsHelper
    def ratings_to_buttons(ratings)
  
    link_to rating.name, rating_path(id: ratable.id), class: 'btn-xs btn-primary'
    end
end

app/views/ratings/_form.html.erb
<!--<div class="form-group">-->

<h2>Rate <%= @rating.ratable.name %></h2>

<!--<#%= f.ratings :ratings %>-->
<%= form_for @rating do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :ratable_id %>
  <%= f.hidden_field :ratable_type %>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

  
<!--</div>-->

app/views/ratings/_list.html.erb
<% unless ratings.empty?  %>
   <%= ratings_to_buttons(ratings) %>
 <% end %>

app/views/ratings/_rating.html.erb
<h4>Rating:
        <% if ratable.rating %>
          <div class="btn-xs btn-primary rating">
            <%= ratable.rating.name %>
          </div>
          
        <% else %>
          <%= link_to "Rate it!", new_rating_path(ratable_id: ratable.id, ratable_type: ratable.class.name)  %>
        <% end %>
        
      </h4>

app/views/ratings/new.html.erb
<%= render "form" %>

app/views/ratings/show.html.erb
<div class="row">
    <div class="col-md-8">
      <h1>Rating:
        <% if @topic.rating %>
          <%= @topic.rating.name %>
        <% else %>
             <%= render partial: "ratings/rating", locals: {ratable: @topic} %>
        <% end %>
   
      </h1>

      <% @rating.topics.each do |topic| %>
        <div>
          Topic: <%= link_to topic.name, topic %>
        </div>
      <% end %>

      <% @rating.posts.each do |post| %>
        <div>
          Post: <%= link_to post.title, topic_post_path(post.topic, post) %>
        </div>
      <% end %>
    </div>
  </div>